### ISSUE TITLE
模板脚手架建议反馈

### ISSUE THREAD

**Issue by bszhct** [bszhct/bs-cli#1]
[template-node](https://github.com/bszhct/template-node)、[template-react](https://github.com/bszhct/template-react)、[template-component](https://github.com/bszhct/template-component) 脚手架以及其中涉及的 [template-eslint](https://github.com/bszhct/template-eslint)、[template-webpack](https://github.com/bszhct/template-webpack) 建议反馈在这条 issue 的评论区，谢谢。

**Comment by Mirdoriss** [comment]
群主脚手架怎么搞得？我想学学

**Comment by bszhct** [comment]
暂时没有哈，目前主要是自用。
